# Site settings
title: Centrarium Theme
email: blcentra@gmail.com
name: Ben Centra
description: > 
  Custom Jekyll theme for Ben Centra's blog, made by Ben Centra. 
  You're welcome to use it as well!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bencentra.com" # the base hostname & protocol for your site

# Disqus comments
disqus_shortname: bencentra

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
# 
# Example:
# 
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter-square                  # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share_url: http://twitter.com/share   # URL for sharing to the service (leave blank to not allow sharing)
#     share_title: ?text=                   # Title parameter for sharing URL
#     share_link: "&amp;url="               # Link parameter for sharing URL

social:
  - name: Twitter
    icon: twitter-square
    username: "@TheBenCentra"
    url: https://twitter.com/TheBenCentra
    desc: Follow me on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - name: Facebook
    icon: facebook-square
    username: thebencentra
    url: 
    desc: Friend me on Facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - name: GitHub
    icon: github
    username: bencentra
    url: https://github.com/bencentra
    desc: Fork me on GitHub
    share_url:
    share_title:
    share_link:

  - name: LinkedIn
    icon: linkedin-square
    username: Ben Centra
    url: https://www.linkedin.com/pub/ben-centra/47/769/60a
    desc: Connect with me on LinkedIn
    share_url: //www.linkedin.com/shareArticle
    share_title: ?mini=true
    share_link: "&amp;url="

  - name: Google+
    icon: google-plus-square
    username: 
    url: 
    desc: Add me to your Circles
    share_url: //plus.google.com/share
    share_title: ?title=
    share_link: "&amp;url="
